### ISSUE TITLE
Marking the fallen

### ISSUE THREAD

**Issue by djcenox** [SkyFireArchives/SkyFireDB#102]
http://www.wowhead.com/quest=27856
Don't work. I posted horde vsersion but i guess alliance version too.

**Comment by Raydeon** [comment]
This quest is now fixed and will be in the next release. I would be interested in knowing the quest id of the alliance version so I can correc that one as well though.

Raydeon

**Comment by djcenox** [comment]
http://www.wowhead.com/quest=27845

**Comment by Raydeon** [comment]
Thank you, I swear wowhead is going downhill... I searched and searched for that quest last night... would only bring up the horde version. I'll get to work on this one now.

Raydeon

**Comment by Raydeon** [comment]
Ok, now both versions of the quest are fixed and will be in the next database release. Topic closed for now 

Raydeon
