### ISSUE TITLE
Quest - Breaking Waves of Change

### ISSUE THREAD

**Issue by olivete** [SkyFireArchives/SkyFireDB#107]
Same problem as issue #106, posted by me too.

http://www.wowhead.com/quest=26385

You accept this quest, go throught the pink portal and find the Flight Master Vesprystus in Rut'theran Village.

By now you should be able to fly to Lor'danel, but you cant, cause you dont have the fly path to there.

Possible solution, make this NPC add the fly path both for its local (Rut' Village) and Lor'danel.

Thanks!

**Comment by Nomadgraphics** [comment]
Hi, I just tested this with a new character. In the new revision of our database you can now fly to Lor'danel from Rut' Village.

enjoy
