### ISSUE TITLE
Portal error

### ISSUE THREAD

**Issue by VeltanV** [SkyFireArchives/SkyFireDB#110]
The portal to Blasted Lands located in Temple of the Moon .It shows an error if the level is below the required one.And Insted of showing the message:"Required level is not met. it shows:"error".I can not find the portal in wowhead.

**Comment by Bootz** [comment]
is this the area you speak of? http://www.wowhead.com/quest=27269#.

**Comment by VeltanV** [comment]
Yes ,that is the area.

**Comment by Raydeon** [comment]
So the issue is that it says the wrong error message? or that the portal doesn't work? Also, please go to the portal and do a .gps, just so I know we are talking about the same portal.

Raydeon

**Comment by VeltanV** [comment]
x:9661.275391 Y:2512.133789 Z:1331.637583 Map:1 Selected none. The portal is working ,the message is not good.

**Comment by Nomadgraphics** [comment]
I just tested this. In current release of our database. The Portal is named "Blasted Lands" I used the Portal and it transported me to The Blasted Lands.

**Comment by VeltanV** [comment]
Dude did i say it was not working? The message you get if you are below the required lvl is "errpr".

**Comment by Nomadgraphics** [comment]
1. I am not "Dude" you can call me Nomad. 
2. I just tested this with a level 10 character it works fine
3. Try and create a new world db and install the release again
4. if that doesn't work try deleting the portal and replace it with this gob: 195141
5. Have a Happy Easter
