### ISSUE TITLE
Save Krennan Aranas

### ISSUE THREAD

**Issue by GnaXi** [SkyFireArchives/SkyFireDB#111]
Quest: Save Krennan Aranas [http://www.wowhead.com/quest=14293]

When jumping onto the horse, you can control the horse yourself (Instead of the horse moving by itself as intended) 
Krennan Aranas is not to be found at his location in the tree.

It's therefore not possible to continue the quest line as Worgen.

A nice description of the quest ca be found on wowhead.com:
"After accepting this quest, you will be given a mount. The horse will run and navigate on its own. Your horse will stop momentarily at the top of some stares before charging. At this point quickly locate and target the person hanging from the tree in front of you, he will be kicking his legs. Worgen will be attacking you. Once targeted, use the action button provided by the mount. Action #1. He will then get on your horse and you will run back. The End.."

**Comment by ludlamzgull** [comment]
confirm

**Comment by Efreet** [comment]
Krennan Aranas got phaseMask 8, he must got phaseMask 4, i believe:

UPDATE creature SET phaseMask=4 WHERE id=35753, --Fix to phase NPC Krennan -> Quest: http://es.wowhead.com/quest=14293

In addition, the spell dont complete the quest, it does not consideration to the objectives. 

Sorry my English :$

**Comment by Nomadgraphics** [comment]
This was fixed in revision 7  thanks to Raydeon for all the hard work
