### ISSUE TITLE
Mastering the Arcane

### ISSUE THREAD

**Issue by GnaXi** [SkyFireArchives/SkyFireDB#112]
Human Mage Quest - Objects missing [http://www.wowhead.com/quest=26916]

Outside Northshire Abbey there should be placed a practice area with Training Dummies.
Screenshot showing the area:
http://www.wowhead.com/quest=26916#screenshots:id=279708

**Comment by GnaXi** [comment]
Object is in place, but wasn't correctly placed on the quest map.

**Comment by Nomadgraphics** [comment]
resolved
