### ISSUE TITLE
Trolling for Information

### ISSUE THREAD

**Issue by GnaXi** [SkyFireArchives/SkyFireDB#118]
Quest: http://www.wowhead.com/quest=24489

Two of the trolls that you are supposed to spy on, will attack you (even though they're not supposed to):
Soothsayer Mirim'koa [http://www.wowhead.com/npc=37174]
Soothsayer Rikkari [http://www.wowhead.com/npc=37173]

The last one will not attack you, but you're still not able to achieve the goal of listening in on her (goes for the others too):
Soothsayer Shi'kala [http://www.wowhead.com/npc=37108]

Description from wowhead of how it should work:
"First two are inside the huts just west of the encampment where you pick up the quest, and then the last one is just outside of the cave south of the encampment...all you need to do is just stand right next to them to tell their story, takes about 5 sec."

**Comment by Nomadgraphics** [comment]
Fixed. 
This will be released in next update.
 I want to give credit to Jorex aka superzoris for sharing this fix.
