### ISSUE TITLE
Ice and Fire

### ISSUE THREAD

**Issue by GnaXi** [SkyFireArchives/SkyFireDB#120]
Quest: http://www.wowhead.com/quest=218

Following NPC's missing from cave:
Grik'nir the Cold [http://www.wowhead.com/npc=808]
Wayward Fire Elemental [http://www.wowhead.com/npc=37112]

Therefore unable to complete objectives.

**Comment by Nomadgraphics** [comment]
Fixed. Will be in next Public release

thank you for the report
