### ISSUE TITLE
Elixirs for the Bladeleafs

### ISSUE THREAD

**Issue by GnaXi** [SkyFireArchives/SkyFireDB#122]
Quest: http://www.wowhead.com/quest=1581

You're able to pick up the quest, even if you're not a Herbalist.
Your Alchemy level also has to be 20 or above, to be able to take the quest.

**Comment by Nomadgraphics** [comment]
although this quest is stated that it is for alchemist it is not necessary for the player to have alchemy and herbalism skills. I personally have done this quest in the past on a 2.4 TBC server. I simply went to the auction house and bought the Elixir of Lion's Strength (6) and Elixir of Minor Defense (2) turned it in, and I received the items and most importantly noted:

Upon completion of this quest you will gain:

```
700 experience
250 reputation with Darnassus
```

xD

**Comment by GnaXi** [comment]
If that's the case, my mistake! =)

**Comment by Nomadgraphics** [comment]
no problem man. It's not a mistake you had a great concern.. it's just that some quest are left alone for people to get rep
