### ISSUE TITLE
Buggy Vehicles

### ISSUE THREAD

**Issue by SkyAngel** [SkyFireArchives/SkyFireDB#123]
All vehicles that are needed for quests in the area worgen and goblins do not work.
Since I do not know whether it is a DB or Core mistake, I Poste is in both categories

**Comment by SkyFire** [comment]
Everytime I see such a "bug report", it reminds me of an old joke:

A group of "mentally-challenged" children goes for school trip by bus. Suddenly the bus stops, the engine won't start again. The driver goes to check, spends an hour in the engine compartment trying to find what's wrong. Little Johnny comes and says, "I know what's wrong, I know what's wrong". The driver disposes of the kid - what could a retard know about engines? After another hour, little Johnny comes again, "I know what's wrong!". The driver is frustrated but sends Johnny away. After yet another unsuccessful hour, little Johnny comes again with his "I know what's wrong! I know what's wrong!" The driver, exhausted, says to himself - there's nothing to lose. "So what's wrong with it, Johnny?"
"It's broooooken!"

Now, do you want to be the retarded little Johnny?

**Comment by SkyAngel** [comment]
Thanks for the "friendly" response.
Since I am not a developer and I have noticed the error, I just wanted him Report
But on the "nice" answer I can give you and absofort will no longer report bugs to me or my gamers noticed that even my bug reports are apparently just a stupid joke
I'd rather not write now what I think, because I can think of now no friendly response...
PS: And yes, I do not speak English well, maybe you fall for this one still a stupid post
