### ISSUE TITLE
Quest : Sacrifices (Gilneas City)

### ISSUE THREAD

**Issue by specters** [SkyFireArchives/SkyFireDB#126]
any script for this quest?

**Comment by LKArthas** [comment]
this is a basic quest if you want to get the worgens out, i think the herse must have an script assigned in the database, but first you need to mount in the horse, and for start the vehicle cursor icon does not show up, maybe in the DB the Horse is not assigned as an NPC

**Comment by specters** [comment]
ok.I know that
I just want the scripts

**Comment by ludlamzgull** [comment]
confirm doesnt work

**Comment by Efreet** [comment]
Anybody know the id of vehicle?

**Comment by Nomadgraphics** [comment]
resolved
