### ISSUE TITLE
Dragons in elwynn forest 

### ISSUE THREAD

**Issue by LKArthas** [SkyFireArchives/SkyFireDB#127]
there are 4 flying dragons from eastvale logging camp (Elwynn forest) heading to stone cairn lake, the dragons are friedly but i think it should not be ther please confirm this and fix it if is possible for the next DB release creatures name (temp NPC)

**Comment by LKArthas** [comment]
there is more dragons around westbrook garrison at least 4 more

**Comment by Nomadgraphics** [comment]
Fixed

will be added to next update
