### ISSUE TITLE
Questen to DB

### ISSUE THREAD

**Issue by SkyAngel** [SkyFireArchives/SkyFireDB#128]
Hello,

I do not mean to seem ungrateful or unhöfflich. I appreciate their work very
I just noticed all the new areas of Cata completely empty of NPCs and mobs are
Can you already see in the distant future, when they will be bespawnt?

Greetings

**Comment by Nomadgraphics** [comment]
of course we will have them spawned correctly. It's a huge project just keep checking back

**Comment by Nomadgraphics** [comment]
bye
