### ISSUE TITLE
Holy light lvl fix 

### ISSUE THREAD

**Issue by LKArthas** [SkyFireArchives/SkyFireDB#129]
i have fixed the holy light Lvl requirement (the game have set to a lvl requirement of 14) but the games shows you that becomes avaible at lvl 7 just run this script in the world DB :)

UPDATE `npc_trainer` SET `reqlevel`=7 WHERE `entry`=927 AND `spell`=635 LIMIT 1;
UPDATE `npc_trainer` SET `reqlevel`=7 WHERE `entry`=928 AND `spell`=635 LIMIT 1;
UPDATE `npc_trainer` SET `reqlevel`=7 WHERE `entry`=5147 AND `spell`=635 LIMIT 1;
UPDATE `npc_trainer` SET `reqlevel`=7 WHERE `entry`=5148 AND `spell`=635 LIMIT 1;
UPDATE `npc_trainer` SET `reqlevel`=7 WHERE `entry`=5149 AND `spell`=635 LIMIT 1;
UPDATE `npc_trainer` SET `reqlevel`=7 WHERE `entry`=5491 AND `spell`=635 LIMIT 1;
UPDATE `npc_trainer` SET `reqlevel`=7 WHERE `entry`=5492 AND `spell`=635 LIMIT 1;
UPDATE `npc_trainer` SET `reqlevel`=7 WHERE `entry`=16679 AND `spell`=635 LIMIT 1;
UPDATE `npc_trainer` SET `reqlevel`=7 WHERE `entry`=16680 AND `spell`=635 LIMIT 1;
UPDATE `npc_trainer` SET `reqlevel`=7 WHERE `entry`=16681 AND `spell`=635 LIMIT 1;
UPDATE `npc_trainer` SET `reqlevel`=7 WHERE `entry`=20406 AND `spell`=635 LIMIT 1;
UPDATE `npc_trainer` SET `reqlevel`=7 WHERE `entry`=23128 AND `spell`=635 LIMIT 1;
UPDATE `npc_trainer` SET `reqlevel`=7 WHERE `entry`=16761 AND `spell`=635 LIMIT 1;
UPDATE `npc_trainer` SET `reqlevel`=7 WHERE `entry`=17483 AND `spell`=635 LIMIT 1;
UPDATE `npc_trainer` SET `reqlevel`=7 WHERE `entry`=17509 AND `spell`=635 LIMIT 1;
UPDATE `npc_trainer` SET `reqlevel`=7 WHERE `entry`=17844 AND `spell`=635 LIMIT 1;
UPDATE `npc_trainer` SET `reqlevel`=7 WHERE `entry`=35281 AND `spell`=635 LIMIT 1;
UPDATE `npc_trainer` SET `reqlevel`=7 WHERE `entry`=43001 AND `spell`=635 LIMIT 1;
UPDATE `npc_trainer` SET `reqlevel`=7 WHERE `entry`=43013 AND `spell`=635 LIMIT 1;
UPDATE `npc_trainer` SET `reqlevel`=7 WHERE `entry`=43795 AND `spell`=635 LIMIT 1;
UPDATE `npc_trainer` SET `reqlevel`=7 WHERE `entry`=44725 AND `spell`=635 LIMIT 1;
UPDATE `npc_trainer` SET `reqlevel`=7 WHERE `entry`=49741 AND `spell`=635 LIMIT 1;
UPDATE `npc_trainer` SET `reqlevel`=7 WHERE `entry`=49793 AND `spell`=635 LIMIT 1;
UPDATE `npc_trainer` SET `reqlevel`=7 WHERE `entry`=49954 AND `spell`=635 LIMIT 1;
UPDATE `npc_trainer` SET `reqlevel`=7 WHERE `entry`=50012 AND `spell`=635 LIMIT 1;
UPDATE `npc_trainer` SET `reqlevel`=7 WHERE `entry`=50023 AND `spell`=635 LIMIT 1;
UPDATE `npc_trainer` SET `reqlevel`=7 WHERE `entry`=50035 AND `spell`=635 LIMIT 1;
UPDATE `npc_trainer` SET `reqlevel`=7 WHERE `entry`=50150 AND `spell`=635 LIMIT 1;
UPDATE `npc_trainer` SET `reqlevel`=7 WHERE `entry`=50160 AND `spell`=635 LIMIT 1;
UPDATE `npc_trainer` SET `reqlevel`=7 WHERE `entry`=8664 AND `spell`=635 LIMIT 1;

**Comment by Nomadgraphics** [comment]
doesn't fix the spell cost
