### ISSUE TITLE
Dead thief at side of Hogger Alive!!

### ISSUE THREAD

**Issue by LKArthas** [SkyFireArchives/SkyFireDB#130]
the dead thief npc is alive and attacking any who approaches, and can´t be attacked at the same time, i think the world Db must put it as Dead, not awake as its he

http://www.wowhead.com/npc=42259

**Comment by Nomadgraphics** [comment]
there is a fix coming for now set his faction to 35 and it will fix the attack issue.

**Comment by LKArthas** [comment]
yes but as wowhead claims he must be dead, it´s easy to change faction in the DB and fix the error i already applied it, but i can´t publish because is not as intended by Blizzard, i think the server must be build to the most perfection, but that is my opinion thanks anyway

**Comment by Nomadgraphics** [comment]
didn't I just say there was a fix coming? I am very much aware that he is supposed to be dead. There are other npc's with this issue. There are condition issues that make this impossible right now so you need to be patient

**Comment by Nomadgraphics** [comment]
Fixed

will be in the upcoming revision
