### ISSUE TITLE
Hoboair Gryphon master in the alliance Hostile

### ISSUE THREAD

**Issue by LKArthas** [SkyFireArchives/SkyFireDB#132]
the gryphon master located in furlbrow Pumpkin patch http://www.wowhead.com/npc=42406 is hostile i have fixed this issue already just insert this into the world DB

UPDATE `creature_template` SET `gossip_menu_id`=4106, `faction_A`=11, `faction_H`=11, `npcflag`=8195, `unit_flags`=768, `flags_extra`=2 WHERE `entry`=42406 LIMIT 1;

**Comment by Nomadgraphics** [comment]
Fixed

this will be in the next database update
