### ISSUE TITLE
Old starting areas Buggy

### ISSUE THREAD

**Issue by SkyAngel** [SkyFireArchives/SkyFireDB#134]
Hello,

the all old starting areas is Buggy
The Areas have not NPCs and therefore can a Gamer not the Class Leveln
z.B The Orgen Areas have a quest, who you boars killen must, the areas have but not boars gespawnt

If only I had the bug, I apologize for the disruption

**Comment by Nomadgraphics** [comment]
wowhead links to quest?

**Comment by Nomadgraphics** [comment]
bah....
