### ISSUE TITLE
Small Bugsammlung again :)

### ISSUE THREAD

**Issue by SkyAngel** [SkyFireArchives/SkyFireDB#135]
Hello,

After a test phase I part with you again to be incurred minor and major bugs, I hope I'm for it in the proper selection and I hope that my reports helpfulness and will not be seen as disturbing :)

General bugs:
- Check out Equipt can not be Disenchanted, he always says no one has the right skill, although it has
- Kvaldir Reaver owning any gold in loot
- The mobs generally make too much DMG as a raptor in Stranglethorn Vale Redridge or does DMG 7000

Classes of bugs:
- The case of spin from the hunter simply falls at the feet and can not be legal
- Lockpicking at the villains always says the skill is too low, although this is not true

Quest Bugs:
- The Death Knight quest Into the Realm of Shadows http://wowdata.getbuffed.com/quest/Into-the-Realm-of-Shadows-12687 is bugged because you nciht ascend to the horse may
- The jeweler Quest Figurine - King of Boars http://wowdata.getbuffed.com/item/Trade-Goods/Figurine-King-of-Boars-65895 and Figurine - Dream Owl http://wowdata.getbuffed.com/item / Trade-Goods/Figurine-Dream-Owl-65894 is buggy, even though you have the items that you can not make the quest
- The jeweler quest in Stormwind are buggy, you get no Illustrious Jewelcrafter's Token
  http://www.wowhead.com/quest=25154
  http://www.wowhead.com/quest=25156
  http://www.wowhead.com/quest=25155
  http://www.wowhead.com/quest=25157

I hope I was able to help a little, some things are not so bad, but I just wanted to report times

**Comment by SkyAngel** [comment]
I forgot to mention the spirit healers do not work properly if you for example on the Goblin dies and goes to releasing it comes to the cemetery from the Barrens or Stranglethorn when you die then you get to the cemetery of Westfall

**Comment by SkyAngel** [comment]
The NPCs in the Worgen Area have a wrong Faction
Dark Ranger Thyala 36312
Forsaken Footsoldier 36810 
The Faction is 35, but should have 7 or 14

**Comment by Nomadgraphics** [comment]
multi-report trashcan
