### ISSUE TITLE
Buggy Quests in Uldum

### ISSUE THREAD

**Issue by SkyAngel** [SkyFireArchives/SkyFireDB#136]
[Battle Zone] http://www.wowhead.com/quest=27990
You can not get into the vehicle to the monster to kill it.

[Idolatry] http://www.wowhead.com/quest=27942
The items to be collected are not on.

[Lockdown!] Http://www.wowhead.com/quest=28193
The visit ends guests (NPCs) are not in place.

[Make Yourself Useful] http://www.wowhead.com/quest=27969
The NPC will motivate you can not address it.

[Missed Me By Zhat Much!] Http://www.wowhead.com/quest=28187
You can address any of the 3 Schnottz.

[The Desert Fox] http://www.wowhead.com/quest=27939
You can not catch the mob.

**Comment by Nomadgraphics** [comment]
muti-report..... trashcan
