### ISSUE TITLE
One Char several times in the character selection

### ISSUE THREAD

**Issue by SkyAngel** [SkyFireArchives/SkyFireDB#137]
Hello,

I have here a character DB error
If there is a general error that you can fix it, or if the error is only with me it might help me how can I fix it

Many players have a character several times in the character selection
If you delete but twice, then all characters are gone

Here's a screenshot to understand what I mean
http://img4.fotos-hochladen.net/uploads/wowscrnshot0429oj8ridutn.jpg

Greetings

**Comment by Naios** [comment]
i can confirm that bug.
But it is a core related bug not db i think.

**Comment by SkyAngel** [comment]
Oh Thx i Poste that Error in the Core Bugtracker

**Comment by Nomadgraphics** [comment]
Core issue CLOSED
