### ISSUE TITLE
Daily Quest to Dalaran

### ISSUE THREAD

**Issue by SkyAngel** [SkyFireArchives/SkyFireDB#138]
Hello.

following cooking quest do not work properly:

http://de.wowhead.com/quest=26227

http://de.wowhead.com/quest=26220

you get reputation, EP and gold, but not the skill + 1 and the oh-so-important cooking awards.

The following do not work properly Juwequest

http://wowdata.buffed.de/quest/Ein-Geschenk-fuer-Lila-25160
The necessary pieces were ground, but you can not complete the quest, because the stones are still in English in the mission log as open.

http://wowdata.buffed.de/quest/Nibbler-Nein-25158

the same problem as gift for Lila

http://wowdata.buffed.de/quest/Elementarglibber-25162

Here you can loot the goo anywhere.

**Comment by Nomadgraphics** [comment]
english please

**Comment by SkyAngel** [comment]
Sorry I did not know that a problem is to press the button English: D
This extra-changed just for you :)

following cooking quest do not work properly:

http://www.wowhead.com/quest=26227

http://www.wowhead.com/quest=26220

you get reputation, EP and gold, but not the skill + 1 and the oh-so-important cooking awards.

The following do not work properly Juwequest

http://www.wowhead.com/quest=25160
The necessary pieces were ground, but you can not complete the quest, because the stones are still in English in the mission log as open.

http://www.wowhead.com/quest=25158

the same problem as gift for Lila

http://www.wowhead.com/quest=25162

Here you can loot the goo anywhere.

**Comment by Nomadgraphics** [comment]
sarcasm in post quote: Sorry I did not know that a problem is to press the button English: D
This extra-changed just for you :)

now your post is gone. Sorry I found the delete button... hey look I am a asshole too
