### ISSUE TITLE
First Aid Trainer

### ISSUE THREAD

**Issue by SkyAngel** [SkyFireArchives/SkyFireDB#139]
Hello,

I'm back.

The following organizations are not in Dalaran to learn, although they are of the teacher in the inventory:

http://wowdata.buffed.de/spell/Dichter-Glutseidenverband-88893

http://wowdata.buffed.de/spell/Feldversorgung-Dichter-Glutseidenverband-74558

**Comment by Nomadgraphics** [comment]
Would it be too much trouble for me to get you to post those links in english? Thank you  and use wowhead

**Comment by SkyAngel** [comment]
Hello,

Here you go
http://www.wowhead.com/spell=88893
http://www.wowhead.com/spell=74558

**Comment by Nomadgraphics** [comment]
In Dalaran the First Aid Trainer is Olisarra the Kind... I have tested this and she in fact does give the spells
