### ISSUE TITLE
New Bug Collection

### ISSUE THREAD

**Issue by SkyAngel** [SkyFireArchives/SkyFireDB#140]
Hello,

and again a new collection of bug me

---

The quests in Tol Barad enter Commendation Badge of Tol Barad per quest, but you get no commendation badges, and therefore can not purchase items
http://www.wowhead.com/currency=391

---

The Portal to Blasted Lands portet but not only brings an Error
Sorry, no link

---

The heroic instances modee not work
The bosses and trash are not on the severity and / or increased life
Also, the loot is the standard in the non Hero instances

---

With the knife should be able to Resurrect, but it does not work
http://www.wowhead.com/item=40772

---

One can not carry heirlooms because he always says the lack of need call

---

At level 20 should automatically for a spell learn worgs Wild hunt, but he does not
http://www.wowhead.com/spell=87840

Greetings

**Comment by SkyFire** [comment]
Please put each bug in it's own report. Also please search first to see if it's been reported.

**Comment by SkyAngel** [comment]
Am I the same all over again to write to individual posts, or was it just a piece of information for the future?

**Comment by Nomadgraphics** [comment]
no more multi bug reports in one frigging report! Next time I just delete them all
