### ISSUE TITLE
Deathmine

### ISSUE THREAD

**Issue by SkyAngel** [SkyFireArchives/SkyFireDB#141]
Hello

All the characters go into the mine death crash the server, then the character even if he is teleported away so broken that when you log in every time the server crashes the Chars

We have tested it with multiple characters

**Comment by SkyFire** [comment]
How is this a DB issue?

**Comment by SkyAngel** [comment]
Oh crap posted in the wrong tab, I'm sorry to be deleted

**Comment by Nomadgraphics** [comment]
Core issue
