### ISSUE TITLE
John J. Keeshan quest

### ISSUE THREAD

**Issue by LKArthas** [SkyFireArchives/SkyFireDB#145]
the quest http://www.wowhead.com/quest=26567 is bugged, its suppossed that you must end the quest with John J. Keeshan under the lakeshire Inn, but the Npc is missing http://www.wowhead.com/npc=43184

**Comment by Nomadgraphics** [comment]
Fixed

This will be included in the next revision

note: I also fix the spawns for Redridge Citizens, Big Earl, and Dumpy too

**Comment by LKArthas** [comment]
ok, thank you nomad

2012/5/6, Nomadgraphics
reply@reply.github.com:
