### ISSUE TITLE
Teleporter in Archerus

### ISSUE THREAD

**Issue by SkyAngel** [SkyFireArchives/SkyFireDB#166]
Hello,

The teleporter in Archerus does not work for phase change
In the first phase, so you have to fly down there and finish a few quests that works properly
However, one must be in phase change again from the bottom upwards Teleport, unfortunately, does the teleport not there
i Hope this is a DB Error, when not im sorry :)

Greetings

**Comment by SkyFire** [comment]
This was fixed some time ago.
