### ISSUE TITLE
14124 - Liberate the Kaja'mite

### ISSUE THREAD

**Issue by andrewjeffree** [SkyFireArchives/SkyFireDB#172]
Get told wrong zone when try to use the Kablooey Bombs, there are chunks already on the ground. Can't loot them. Tried adding to inventory with additem and still can't complete quest.

http://www.wowhead.com/quest=14124

**Comment by Heraclion** [comment]
confirm

**Comment by SkyFire** [comment]
Looks like the loot item may be missing. I will check this out.

**Comment by ScrWoW** [comment]
I try to compare the close to realization worgen quest with supply crate and make it look same in DB.
It works now BUT can't complete quest... It looks like completed but "complete" button is diseabled when you try to press it.
