### ISSUE TITLE
313 - Forced to Watch from Afar

### ISSUE THREAD

**Issue by andrewjeffree** [SkyFireArchives/SkyFireDB#173]
NPC's are hostile, and cannot complete quest. 
http://www.wowhead.com/quest=313/forced-to-watch-from-afar

**Comment by SkyFire** [comment]
Post on the correct bug tracker. The DB bug tracker.

**Comment by andrewjeffree** [comment]
erm isn't this the DB bug tracker?

**Comment by andrewjeffree** [comment]
yeah wtf...
