### ISSUE TITLE
linux_installer error

### ISSUE THREAD

**Issue by Abrek** [SkyFireArchives/SkyFireDB#18]
linux_installer.sh: 77: Syntax error: "elif" unexpected (expecting "done")

**Comment by tortosi** [comment]
If you use the linux installer of master branch, work perfectly

Only fail rebase installer.

**Comment by Subv** [comment]
please submit a pull request

**Comment by tortosi** [comment]
this is the path generated between the file that works and not.

http://pastebin.com/WZ3sHXni

**Comment by Subv** [comment]
fixed
