### ISSUE TITLE
37 - Find the Lost Guards, 45 - Discover Rolf's Fate

### ISSUE THREAD

**Issue by andrewjeffree** [SkyFireArchives/SkyFireDB#180]
http://www.wowhead.com/quest=37
http://www.wowhead.com/quest=45
A half-eaten body (72.7, 60.4) is missing, quest can't be turned in to it.

Even if 37 is completed manually, but 45 is also broken so it's a waste.

-Object exists in the database, but I'm unable to add it. Tells me it doesn't exist.

is the .gobject command broken?

**Comment by Chpgmr** [comment]
its a creature not a game object

it is there for me

.gobject commands are fine

not sure about 45

**Comment by andrewjeffree** [comment]
The only creature I can find with the name half-eaten body turns out as a winged demon guy. 

Also there is a game object with the id 55 that has the right name.

**Comment by Chpgmr** [comment]
are you using the 8th skyfire database?

because i just did the quests without issues

**Comment by andrewjeffree** [comment]
yes

**Comment by Chpgmr** [comment]
that is weird, i just did them again without an issue, both 37 and 45

**Comment by andrewjeffree** [comment]
I guess I can redo my world database again >_> thankfully I have a copy of all the patches I've made to fix quests.

**Comment by Chpgmr** [comment]
or just rename the world database to world2 for now and import a new world database

**Comment by andrewjeffree** [comment]
Yeah I did that, how strange... maybe I missed a patch or something the quest is working now...
