### ISSUE TITLE
NPC - Torren Squarejaw

### ISSUE THREAD

**Issue by andrewjeffree** [SkyFireArchives/SkyFireDB#185]
Has a question mark above his head. Despite not having any quests involving him. There are quests that are related on an item drop. But I do not have them.

http://mop.wowhead.com/npc=1153/torren-squarejaw

**Comment by Chpgmr** [comment]
INSERT INTO `gameobject_questrelation` (`id`, `quest`) VALUES 
(194387, 13656),
(194378, 13655),
(194388, 13657),
(194389, 13658),
(194391, 13660),
(194390, 13659);

**Comment by AriDEV** [comment]
NPC is added in 1.11.1 but CARE! ... quests are added in 5.3.0!
