### ISSUE TITLE
6387 - Honor Students

### ISSUE THREAD

**Issue by andrewjeffree** [SkyFireArchives/SkyFireDB#186]
Quest is given from the wrong npc, in the wrong town even.

Quest should be given by Gremlock Pilsnor in Kharanos

Is currently given by Brock Stoneseeker in Thelsamar

Gryphon NPC in Thelsamar also has the follow up quest, that should be in kharanos

Also some of the quest text is wrong, picks? it's cleavers.

http://www.wowhead.com/quest=6387/honor-students

**Comment by Chpgmr** [comment]
May have been one of those quests that blizzard just merely tweaked.

**Comment by andrewjeffree** [comment]
yeah it certainly is something they've tweaked. The text is just slightly changed from the quest that brock stoneseeker used to give

**Comment by Chpgmr** [comment]
REPLACE INTO `creature_template` (`entry`, `difficulty_entry_1`, `difficulty_entry_2`, `difficulty_entry_3`, `KillCredit1`, `KillCredit2`, `modelid1`, `modelid2`, `modelid3`, `modelid4`, `name`, `subname`, `IconName`, `gossip_menu_id`, `minlevel`, `maxlevel`, `exp`, `faction_A`, `faction_H`, `npcflag`, `speed_walk`, `speed_run`, `scale`, `rank`, `mindmg`, `maxdmg`, `dmgschool`, `attackpower`, `dmg_multiplier`, `baseattacktime`, `rangeattacktime`, `unit_class`, `unit_flags`, `dynamicflags`, `family`, `trainer_type`, `trainer_spell`, `trainer_class`, `trainer_race`, `minrangedmg`, `maxrangedmg`, `rangedattackpower`, `type`, `type_flags`, `lootid`, `pickpocketloot`, `skinloot`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `resistance5`, `resistance6`, `spell1`, `spell2`, `spell3`, `spell4`, `spell5`, `spell6`, `spell7`, `spell8`, `PetSpellDataId`, `VehicleId`, `mingold`, `maxgold`, `AIName`, `MovementType`, `InhabitType`, `Health_mod`, `Mana_mod`, `Armor_mod`, `RacialLeader`, `questItem1`, `questItem2`, `questItem3`, `questItem4`, `questItem5`, `questItem6`, `movementId`, `RegenHealth`, `equipment_id`, `mechanic_immune_mask`, `flags_extra`, `ScriptName`, `WDBVerified`) VALUES (1699, 0, 0, 0, 0, 0, 3435, 0, 0, 0, 'Gremlock Pilsnor', 'Cooking Trainer', NULL, 0, 10, 10, 0, 55, 55, 83, 1, 1, 1, 0, 13, 17, 0, 42, 1, 2000, 0, 1, 512, 2048, 0, 2, 0, 0, 0, 9, 13, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', 0, 3, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1699, 0, 2, '', 12340);

DELETE FROM `creature_questrelation` WHERE `id` = 1681;
DELETE FROM `creature_questrelation` WHERE `id` = 1699;

INSERT INTO `creature_questrelation` (`id`, `quest`) VALUES (1699, 6387);
