### ISSUE TITLE
Equip items missing

### ISSUE THREAD

**Issue by w5860363** [SkyFireArchives/SkyFireDB#191]
NPC：45320 http://www.wowhead.com/npc=45320
NPC：39834 http://www.wowhead.com/npc=38934
creature_equip_template table is empty Hope to repair under

**Comment by AriDEV** [comment]
Hi i Have Updated Maievs Weapons :)

the orc dont exist anymore since 403 :) so there is no reason to fix hes weapons :)

http://www.projectskyfire.org/index.php?/topic/9487-equipment-template-captain-saynna-stormrunner-barrow-deeps-watcher/

Can by CLOSED !

**Comment by Nomadgraphics** [comment]
Good job AriDev
