### ISSUE TITLE
Orgrimmar jamus'Vaz vendor FIX

### ISSUE THREAD

**Issue by Slikker** [SkyFireArchives/SkyFireDB#192]
I saw that the item entries was wrong. some double entries, some wrong entries.. All fixed

**Comment by Slikker** [comment]
DELETE FROM `npc_vendor` WHERE (`entry`=46556);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`) VALUES 
(46556, 0, 58180, 0, 0, 3034),
(46556, 0, 58181, 0, 0, 3034),
(46556, 0, 58182, 0, 0, 3034),
(46556, 0, 58183, 0, 0, 3034),
(46556, 0, 58184, 0, 0, 3034),
(46556, 0, 58185, 0, 0, 3035),
(46556, 0, 58187, 0, 0, 3035),
(46556, 0, 58188, 0, 0, 3035),
(46556, 0, 58189, 0, 0, 3035),
(46556, 0, 58190, 0, 0, 3035),
(46556, 0, 58191, 0, 0, 3035),
(46556, 0, 58192, 0, 0, 3035),
(46556, 0, 58193, 0, 0, 3035),
(46556, 0, 58194, 0, 0, 3035),
(46556, 0, 58195, 0, 0, 3034),
(46556, 0, 58197, 0, 0, 3034),
(46556, 0, 58198, 0, 0, 3034),
(46556, 0, 58199, 0, 0, 3034),
(46556, 0, 58481, 0, 0, 3034),
(46556, 0, 58482, 0, 0, 3034),
(46556, 0, 58484, 0, 0, 3034),
(46556, 0, 58485, 0, 0, 3034),
(46556, 0, 58486, 0, 0, 3034),
(46556, 0, 60243, 0, 0, 3049),
(46556, 0, 60244, 0, 0, 3033),
(46556, 0, 60245, 0, 0, 3033),
(46556, 0, 60246, 0, 0, 3043),
(46556, 0, 60247, 0, 0, 3034),
(46556, 0, 60248, 0, 0, 3034),
(46556, 0, 60249, 0, 0, 3050),
(46556, 0, 60250, 0, 0, 3033),
(46556, 0, 60251, 0, 0, 3033),
(46556, 0, 60252, 0, 0, 3044),
(46556, 0, 60253, 0, 0, 3044),
(46556, 0, 60254, 0, 0, 3033),
(46556, 0, 60255, 0, 0, 3033),
(46556, 0, 60256, 0, 0, 3050),
(46556, 0, 60257, 0, 0, 3034),
(46556, 0, 60258, 0, 0, 3050),
(46556, 0, 60259, 0, 0, 3033),
(46556, 0, 60261, 0, 0, 3033),
(46556, 0, 60262, 0, 0, 3044),
(46556, 0, 60275, 0, 0, 3034),
(46556, 0, 60276, 0, 0, 3033),
(46556, 0, 60277, 0, 0, 3049),
(46556, 0, 60278, 0, 0, 3033),
(46556, 0, 60279, 0, 0, 3043),
(46556, 0, 60280, 0, 0, 3034),
(46556, 0, 60281, 0, 0, 3033),
(46556, 0, 60282, 0, 0, 3049),
(46556, 0, 60283, 0, 0, 3033),
(46556, 0, 60284, 0, 0, 3043),
(46556, 0, 65203, 0, 0, 3147),
(46556, 0, 60285, 0, 0, 3034),
(46556, 0, 60286, 0, 0, 3049),
(46556, 0, 65190, 0, 0, 3051),
(46556, 0, 60287, 0, 0, 3033),
(46556, 0, 60288, 0, 0, 3033),
(46556, 0, 60289, 0, 0, 3043),
(46556, 0, 60290, 0, 0, 3034),
(46556, 0, 60298, 0, 0, 3034),
(46556, 0, 60299, 0, 0, 3049),
(46556, 0, 60300, 0, 0, 3033),
(46556, 0, 60301, 0, 0, 3033),
(46556, 0, 60302, 0, 0, 3043),
(46556, 0, 60303, 0, 0, 3051),
(46556, 0, 60304, 0, 0, 3033),
(46556, 0, 60305, 0, 0, 3033),
(46556, 0, 60306, 0, 0, 3045),
(46556, 0, 60307, 0, 0, 3034),
(46556, 0, 60308, 0, 0, 3051),
(46556, 0, 60309, 0, 0, 3033),
(46556, 0, 60310, 0, 0, 3033),
(46556, 0, 60311, 0, 0, 3045),
(46556, 0, 60312, 0, 0, 3034),
(46556, 0, 60313, 0, 0, 3033),
(46556, 0, 60314, 0, 0, 3034),
(46556, 0, 60315, 0, 0, 3051),
(46556, 0, 60316, 0, 0, 3033),
(46556, 0, 60317, 0, 0, 3045),
(46556, 0, 60318, 0, 0, 3033),
(46556, 0, 60319, 0, 0, 3034),
(46556, 0, 60320, 0, 0, 3051),
(46556, 0, 60321, 0, 0, 3033),
(46556, 0, 60322, 0, 0, 3045),
(46556, 0, 60323, 0, 0, 3033),
(46556, 0, 60324, 0, 0, 3033),
(46556, 0, 60325, 0, 0, 3051),
(46556, 0, 60326, 0, 0, 3034),
(46556, 0, 60327, 0, 0, 3045),
(46556, 0, 60328, 0, 0, 3051),
(46556, 0, 60329, 0, 0, 3033),
(46556, 0, 60330, 0, 0, 3033),
(46556, 0, 60331, 0, 0, 3045),
(46556, 0, 60332, 0, 0, 3034),
(46556, 0, 60339, 0, 0, 3033),
(46556, 0, 60340, 0, 0, 3034),
(46556, 0, 60341, 0, 0, 3049),
(46556, 0, 60342, 0, 0, 3033),
(46556, 0, 60343, 0, 0, 3043),
(46556, 0, 60344, 0, 0, 3033),
(46556, 0, 60345, 0, 0, 3034),
(46556, 0, 60346, 0, 0, 3050),
(46556, 0, 60347, 0, 0, 3033),
(46556, 0, 60348, 0, 0, 3044),
(46556, 0, 60349, 0, 0, 3033),
(46556, 0, 60350, 0, 0, 3034),
(46556, 0, 60351, 0, 0, 3049),
(46556, 0, 65186, 0, 0, 3051),
(46556, 0, 60352, 0, 0, 3033),
(46556, 0, 60353, 0, 0, 3043),
(46556, 0, 60354, 0, 0, 3033),
(46556, 0, 60355, 0, 0, 3034),
(46556, 0, 60356, 0, 0, 3050),
(46556, 0, 60357, 0, 0, 3033),
(46556, 0, 60358, 0, 0, 3044),
(46556, 0, 60359, 0, 0, 3050),
(46556, 0, 60360, 0, 0, 3033),
(46556, 0, 60361, 0, 0, 3033),
(46556, 0, 65222, 0, 0, 3034),
(46556, 0, 60362, 0, 0, 3044),
(46556, 0, 60363, 0, 0, 3034),
(46556, 0, 64671, 0, 0, 3037),
(46556, 0, 64672, 0, 0, 3037),
(46556, 0, 64673, 0, 0, 3037),
(46556, 0, 64674, 0, 0, 3037),
(46556, 0, 64676, 0, 0, 3037),
(46556, 0, 65000, 0, 0, 3329),
(46556, 0, 65001, 0, 0, 3329),
(46556, 0, 65002, 0, 0, 3329),
(46556, 0, 65087, 0, 0, 3329),
(46556, 0, 65088, 0, 0, 3329),
(46556, 0, 65089, 0, 0, 3329),
(46556, 0, 65179, 0, 0, 3085),
(46556, 0, 65180, 0, 0, 3145),
(46556, 0, 65181, 0, 0, 3069),
(46556, 0, 65182, 0, 0, 3113),
(46556, 0, 65183, 0, 0, 3136),
(46556, 0, 65184, 0, 0, 3084),
(46556, 0, 65185, 0, 0, 3146),
(46556, 0, 65186, 0, 0, 3068),
(46556, 0, 65187, 0, 0, 3112),
(46556, 0, 65188, 0, 0, 3135),
(46556, 0, 65189, 0, 0, 3147),
(46556, 0, 65190, 0, 0, 3067),
(46556, 0, 65191, 0, 0, 3111),
(46556, 0, 65192, 0, 0, 3093),
(46556, 0, 65193, 0, 0, 3134),
(46556, 0, 65194, 0, 0, 3148),
(46556, 0, 65195, 0, 0, 3066),
(46556, 0, 65196, 0, 0, 3110),
(46556, 0, 65197, 0, 0, 3092),
(46556, 0, 65198, 0, 0, 3133),
(46556, 0, 65199, 0, 0, 3149),
(46556, 0, 65200, 0, 0, 3065),
(46556, 0, 65201, 0, 0, 3109),
(46556, 0, 65202, 0, 0, 3091),
(46556, 0, 65203, 0, 0, 3132),
(46556, 0, 65204, 0, 0, 3083),
(46556, 0, 65205, 0, 0, 3150),
(46556, 0, 65206, 0, 0, 3064),
(46556, 0, 65207, 0, 0, 3108),
(46556, 0, 65208, 0, 0, 3131),
(46556, 0, 65209, 0, 0, 3151),
(46556, 0, 65210, 0, 0, 3090),
(46556, 0, 65211, 0, 0, 3107),
(46556, 0, 65212, 0, 0, 3090),
(46556, 0, 65213, 0, 0, 3151), 
(46556, 0, 65214, 0, 0, 3082),
(46556, 0, 65215, 0, 0, 3152),
(46556, 0, 65216, 0, 0, 3062),
(46556, 0, 65217, 0, 0, 3106),
(46556, 0, 65218, 0, 0, 3129),
(46556, 0, 65219, 0, 0, 3081),
(46556, 0, 65220, 0, 0, 3153),
(46556, 0, 65221, 0, 0, 3061),
(46556, 0, 65222, 0, 0, 3105),
(46556, 0, 65223, 0, 0, 3128),
(46556, 0, 65224, 0, 0, 3080),
(46556, 0, 65225, 0, 0, 3154),
(46556, 0, 65226, 0, 0, 3060),
(46556, 0, 65227, 0, 0, 3104),
(46556, 0, 65228, 0, 0, 3127),
(46556, 0, 65229, 0, 0, 3155),
(46556, 0, 65230, 0, 0, 3117),
(46556, 0, 65231, 0, 0, 3103),
(46556, 0, 65232, 0, 0, 3089),
(46556, 0, 65233, 0, 0, 3126),
(46556, 0, 65234, 0, 0, 3156),
(46556, 0, 65235, 0, 0, 3059),
(46556, 0, 65236, 0, 0, 3102),
(46556, 0, 65237, 0, 0, 3088),
(46556, 0, 65238, 0, 0, 3125),
(46556, 0, 65239, 0, 0, 3079),
(46556, 0, 65240, 0, 0, 3157),
(46556, 0, 65241, 0, 0, 3058),
(46556, 0, 65242, 0, 0, 3101),
(46556, 0, 65243, 0, 0, 3124),
(46556, 0, 65244, 0, 0, 3078),
(46556, 0, 65245, 0, 0, 3158),
(46556, 0, 65246, 0, 0, 3057),
(46556, 0, 65247, 0, 0, 3100),
(46556, 0, 65248, 0, 0, 3123),
(46556, 0, 65249, 0, 0, 3077),
(46556, 0, 65250, 0, 0, 3159),
(46556, 0, 65251, 0, 0, 3053),
(46556, 0, 65252, 0, 0, 3099),
(46556, 0, 65253, 0, 0, 3122),
(46556, 0, 65254, 0, 0, 3076),
(46556, 0, 65255, 0, 0, 3144),
(46556, 0, 65256, 0, 0, 3052),
(46556, 0, 65257, 0, 0, 3098),
(46556, 0, 65258, 0, 0, 3121),
(46556, 0, 65259, 0, 0, 3143),
(46556, 0, 65260, 0, 0, 3072),
(46556, 0, 65261, 0, 0, 3116),
(46556, 0, 65262, 0, 0, 3094),
(46556, 0, 65263, 0, 0, 3139),
(46556, 0, 65264, 0, 0, 3087),
(46556, 0, 65265, 0, 0, 3160),
(46556, 0, 65266, 0, 0, 3071),
(46556, 0, 65267, 0, 0, 3115),
(46556, 0, 65268, 0, 0, 3138),
(46556, 0, 65269, 0, 0, 3086),
(46556, 0, 65270, 0, 0, 3161),
(46556, 0, 65271, 0, 0, 3070),
(46556, 0, 65272, 0, 0, 3114),
(46556, 0, 65273, 0, 0, 3137),
(46556, 0, 67423, 0, 0, 3329),
(46556, 0, 67424, 0, 0, 3329),
(46556, 0, 67425, 0, 0, 3329),
(46556, 0, 67426, 0, 0, 3329),
(46556, 0, 67427, 0, 0, 3329),
(46556, 0, 67428, 0, 0, 3329),
(46556, 0, 67429, 0, 0, 3329),
(46556, 0, 67430, 0, 0, 3329),
(46556, 0, 67431, 0, 0, 3329),
(46556, 0, 68812, 0, 0, 3035);

**Comment by Slikker** [comment]
will be doing the ally side tomorrow.. well later today.. :P

**Comment by IRComputer** [comment]
Took us the whole night & a bottle of brandy :)

**Comment by Slikker** [comment]
sorry still one more item fix 
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`) VALUES 
(46556, 0, 65213, 0, 0, 3031),
