### ISSUE TITLE
 No NPCs and Monsters ( Invisible! )

### ISSUE THREAD

**Issue by spl1nter** [SkyFireArchives/SkyFireDB#195]
In Duskhaven i can´t see something as normal player. As GM i can see all NPCs and Monsters. Where is the Bug and how i can fix this?

SkyFire_DB_NG_Release_9_07_29_2012

Thx

**Comment by Heraclion** [comment]
in table creature you must change the phasemask,also if it's the right phasemask,go in creature_template_addon and delete the entry from there

**Comment by DigiD702** [comment]
I was able to see the NPC's must have been fixed.

-Closed
