### ISSUE TITLE
some base bug

### ISSUE THREAD

**Issue by Arsalan0098** [SkyFireArchives/SkyFireDB#196]
I Need ur Immediate help for find good core or repack for 4.3.4
actually i use trinity core & mangoose core for 4.3.4 server but they have base bug & i can't fix them
Even i use repacks by strawberry & Holystone-Productions but they have this bug too
for exp for trinity when i chose race worgen i can't lvl up even 2 lvl cause after take 1quest phase 1 can't go to phase 2 for other quest & stuck
we test phase 2 npc for take next quest's but map can't change phase for done quest & out of gilneas
& on gilneas u can see little deamon (warlock pet) none selceted
fire in game can't burn u :|
but on goblin's race we have a big problem cause on lost isles u can't find even one npc or mob :|
all gone :-??
for other race when u chose them after login all npc have quest alarm on them head & in other race mob's & guard on battle & u can't done quest's
i don't know what to do :(( plz help me
one question in my head is why when core 4.3.4 have base bug they go for fix dangeun & raid bug's ???  really why?? how they

**Comment by SkyFire** [comment]
No repack support here! EVER! Go bug TC about there 4.3.4 DB not our problem.
