### ISSUE TITLE
Table `instance_encounters` has an invalid encounter id 161, skipped!

### ISSUE THREAD

**Issue by gpcore** [SkyFireArchives/SkyFireDB#23]
Table `instance_encounters` has an invalid encounter id 161, skipped!

that mean, core not support this dungeon script?

**Comment by ghost** [comment]
on which core is that?

**Comment by Subv** [comment]
on rebase

**Comment by gpcore** [comment]
rebase. i read somthing about core not support dungeon system? its port from mangos just or i miss somthing?
