### ISSUE TITLE
Fix for Database_Installer_Updater

### ISSUE THREAD

**Issue by hguy23** [SkyFireArchives/SkyFireDB#24]
You must change in Database_Installer_Updater this 

SET dumppath=.\dump\
SET mysqlpath=.\dep\mysql\
SET devsql=.\main_db\world\
SET procsql=.\main_db\procs\
SET changsql=.\world_updates\

to 

SET dumppath=.\dump
SET mysqlpath=.\dep\mysql
SET devsql=.\main_db\world
SET procsql=.\main_db\procs
SET changsql=.\world_updates

**Comment by SkyFire** [comment]
Your right. I had it there on my other revision. But I pushed the wrong one.
