### ISSUE TITLE
Quest: All Hell Breaks Loose

### ISSUE THREAD

**Issue by LetsWoW** [SkyFireArchives/SkyFireDB#28]
Rampaging Worgen can not attack
Fix: 

UPDATE `creature_template` SET `faction_A` = 7, `faction_H` = 7, `npcflag` = 0, `flags_extra` = 64 WHERE `entry` = 34884;

**Comment by SkyFire** [comment]
Will review this fix.

**Comment by SkyFire** [comment]
Will add this to our update pack. Thanks.

**Comment by Raydeon** [comment]
Added to latest release
