### ISSUE TITLE
NPC: Gilneas City Guard

### ISSUE THREAD

**Issue by LetsWoW** [SkyFireArchives/SkyFireDB#29]
Gilneas City Guard has wrong Faction and npcflag

FIX:
UPDATE `creature_template` SET `faction_A` = 2164, `faction_H` = 2164, `npcflag` = 67108864 WHERE `entry` = 34916;

**Comment by SkyFire** [comment]
Will review this fix.

**Comment by SkyFire** [comment]
Will add this to our update pack. Thanks.

**Comment by Raydeon** [comment]
added to latest release
