### ISSUE TITLE
Questbug - "Murder Was The Case That They Gave Me"

### ISSUE THREAD

**Issue by WoweePaw** [SkyFireArchives/SkyFireDB#3]
you can't speak with the various homeless people , so that you can't get some clues.

Additional-Infos:
http://www.wowhead.com/quest=26209

**Comment by SkyFire** [comment]
May need to be scripted in SmartAI. Will leave this open for now.

**Comment by WoweePaw** [comment]
kay...I hope someone can fix this :)

**Comment by Subv** [comment]
http://www.projectskyfire.org/index.php/topic/4607-smartscriptwipquest-murder-was-the-case-they-gave-me/

Its completable with this change, but its not yet complete
