### ISSUE TITLE
Quest: The Curse of the Tombs

### ISSUE THREAD

**Issue by LetsWoW** [SkyFireArchives/SkyFireDB#30]
NPC Crazed Digger not spawend need for quest The Curse of the Tombs http://www.wowhead.com/quest=27755
FIX: 

DELETE FROM `creature` WHERE `id`=46590;
INSERT INTO `creature` (`guid`,`id`,`map`,`spawnMask`,`phaseMask`,`modelid`,`equipment_id`,`position_x`,`position_y`,`position_z`,`orientation`,`spawntimesecs`,`spawndist`,`currentwaypoint`,`curhealth`,`curmana`,`MovementType`,`npcflag`,`unit_flags`,`dynamicflags`) VALUES
(@, 46590, 1, 1, 1, 0, 0, -10527.9, -1894.11, 91.2724, 0.634032, 600, 0, 0, 42, 0, 0, 0, 0, 0),
(@, 46590, 1, 1, 1, 0, 0, -10472.9, -1896.52, 90.3225, 1.93778, 600, 0, 0, 42, 0, 0, 0, 0, 0),
(@, 46590, 1, 1, 1, 0, 0, -10460.3, -1913.05, 90.3231, 1.77678, 600, 0, 0, 42, 0, 0, 0, 0, 0),
(@, 46590, 1, 1, 1, 0, 0, -10452.7, -1914.82, 90.3508, 3.57141, 600, 0, 0, 42, 0, 0, 0, 0, 0),
(@, 46590, 1, 1, 1, 0, 0, -10442.9, -1909.79, 90.3572, 4.08978, 600, 0, 0, 42, 0, 0, 0, 0, 0),
(@, 46590, 1, 1, 1, 0, 0, -10432.5, -1901.59, 86.3446, 0.645805, 600, 0, 0, 42, 0, 0, 0, 0, 0),
(@, 46590, 1, 1, 1, 0, 0, -10445.1, -1900.61, 90.3234, 5.52313, 600, 0, 0, 42, 0, 0, 0, 0, 0),
(@, 46590, 1, 1, 1, 0, 0, -10451, -1890.41, 90.3234, 5.63309, 600, 0, 0, 42, 0, 0, 0, 0, 0),
(@, 46590, 1, 1, 1, 0, 0, -10457.3, -1883.85, 90.3234, 4.34111, 600, 0, 0, 42, 0, 0, 0, 0, 0),
(@, 46590, 1, 1, 1, 0, 0, -10450.1, -1875.76, 90.4393, 5.06368, 600, 0, 0, 42, 0, 0, 0, 0, 0),
(@, 46590, 1, 1, 1, 0, 0, -10466, -1851.4, 92.6065, 1.52939, 600, 0, 0, 42, 0, 0, 0, 0, 0),
(@, 46590, 1, 1, 1, 0, 0, -10477.3, -1861.86, 91.4511, 1.8514, 600, 0, 0, 42, 0, 0, 0, 0, 0),
(@, 46590, 1, 1, 1, 0, 0, -10480, -1862.76, 91.1783, 1.91816, 600, 0, 0, 42, 0, 0, 0, 0, 0),
(@, 46590, 1, 1, 1, 0, 0, -10497, -1903.14, 90.9902, 4.76915, 600, 0, 0, 42, 0, 0, 0, 0, 0),
(@, 46590, 1, 1, 1, 0, 0, -10492, -1881.43, 90.3237, 4.66705, 600, 0, 0, 42, 0, 0, 0, 0, 0),
(@, 46590, 1, 1, 1, 0, 0, -10493.9, -1869.28, 90.3237, 5.14222, 600, 0, 0, 42, 0, 0, 0, 0, 0),
(@, 46590, 1, 1, 1, 0, 0, -10497.6, -1862.39, 90.4961, 5.61346, 600, 0, 0, 42, 0, 0, 0, 0, 0),
(@, 46590, 1, 1, 1, 0, 0, -10508.2, -1871.72, 90.3239, 1.24664, 600, 0, 0, 42, 0, 0, 0, 0, 0),
(@, 46590, 1, 1, 1, 0, 0, -10511.9, -1876.55, 90.3239, 0.288457, 600, 0, 0, 42, 0, 0, 0, 0, 0),
(@, 46590, 1, 1, 1, 0, 0, -10519.4, -1879.65, 90.3239, 1.81213, 600, 0, 0, 42, 0, 0, 0, 0, 0),
(@, 46590, 1, 1, 1, 0, 0, -10538.9, -1891.77, 92.2704, 4.46285, 600, 0, 0, 42, 0, 0, 0, 0, 0),
(@, 46590, 1, 1, 1, 0, 0, -10529.3, -1879.28, 90.6953, 3.65389, 600, 0, 0, 42, 0, 0, 0, 0, 0),
(@, 46590, 1, 1, 1, 0, 0, -10521.2, -1869.43, 90.3234, 5.77446, 600, 0, 0, 42, 0, 0, 0, 0, 0),
(@, 46590, 1, 1, 1, 0, 0, -10531.1, -1860.69, 90.324, 5.32286, 600, 0, 0, 42, 0, 0, 0, 0, 0);

**Comment by Bootz** [comment]
Blizz - power...
any ideas on fixing the last two quests in chain: last rights? 
http://www.wowhead.com/quest=11942 ~two bug bosses not working.
http://www.wowhead.com/quest=12019 ~the whole platform quest is all outta whack!
this fix for platform can go to trinity as well...

**Comment by SkyFire** [comment]
Will review this fix.

**Comment by LetsWoW** [comment]
http://www.wowhead.com/quest=11942
you can fix the boss with SAI

**Comment by SkyFire** [comment]
Will add this to our update pack. Thanks.

**Comment by Raydeon** [comment]
added to latest release
