### ISSUE TITLE
Quest: The Cypher of Keset

### ISSUE THREAD

**Issue by LetsWoW** [SkyFireArchives/SkyFireDB#31]
NPC Raider Lord Havat not Spawned

FIX: 
DELETE FROM `creature` WHERE `id`=49214;
INSERT INTO `creature` (`guid`,`id`,`map`,`spawnMask`,`phaseMask`,`modelid`,`equipment_id`,`position_x`,`position_y`,`position_z`,`orientation`,`spawntimesecs`,`spawndist`,`currentwaypoint`,`curhealth`,`curmana`,`MovementType`,`npcflag`,`unit_flags`,`dynamicflags`) VALUES
(@, 49214, 1, 1, 1, 0, 0, -9923.66, -2383.77, 14.2765, 1.80046, 600, 0, 0, 84, 0, 0, 0, 0, 0);

**Comment by SkyFire** [comment]
Will review this fix.

**Comment by SkyFire** [comment]
Will add this to our update pack. Thanks.

**Comment by Raydeon** [comment]
Added to latest release

**Comment by SkyAngel** [comment]
Is again bugged

The Cypher Of Keset of Salhet:
http://www.wowhead.com/quest=28500
Task: Obtain the "Code of Keset".
Error: The Raiders are looking NPC Lord Havat drops the desired item (Wowhead link), it is also counted, you can not, however, the quest abshließen. The message "Task completed" after the loot does not appear.
