### ISSUE TITLE
Quest: In Need of Ingredients

### ISSUE THREAD

**Issue by LetsWoW** [SkyFireArchives/SkyFireDB#33]
In Need of Ingredients http://www.wowhead.com/quest=14320
You can not the quest closed by the Quest taker

Fix:
UPDATE quest_template SET QuestFlags = 65536 WHERE entry = 14320;

**Comment by Raydeon** [comment]
If you wish to auto-complete the quest for your private server, that is up to you. However, we are still in development in this database. Therefore, we will NOT autocomplete quests, as they make it difficult to locate and correct them. We will however, add this quest to my list of quests needing work. We appreciate the input, but in the future, can you please explain why the quest cannot be completed as normal?

Raydeon

**Comment by LetsWoW** [comment]
Blizzlike Fix: UPDATE quest_template SET QuestFlags = 65536 WHERE entry = 14320; 
autocomplete on Blizzserver per QuestFlags ;)
