### ISSUE TITLE
Quest: You Can't Take 'Em Alone

### ISSUE THREAD

**Issue by LetsWoW** [SkyFireArchives/SkyFireDB#34]
Object Black Gunpowder Keg has wrong Phasemask

Fix:
UPDATE `gameobject` SET `phasemask` = '1' WHERE `id` = 196403;

**Comment by Raydeon** [comment]
I will check into this. Thank you for the input.

Raydeon

**Comment by Raydeon** [comment]
All fixes now need to be done through the forums... This one can be found here
 http://www.projectskyfire.org/index.php?/topic/6690-skyfiredb-fix-submissions-from-blizz-power/

Thanks again for the submission,
 Raydeon
