### ISSUE TITLE
Quest: John J. Keeshan

### ISSUE THREAD

**Issue by LetsWoW** [SkyFireArchives/SkyFireDB#35]
NPC John J. Keeshan not spawned http://www.wowhead.com/npc=43184

Fix:
DELETE FROM `creature` WHERE `id`=43184;
INSERT INTO `creature` (`guid`,`id`,`map`,`spawnMask`,`phaseMask`,`modelid`,`equipment_id`,`position_x`,`position_y`,`position_z`,`orientation`,`spawntimesecs`,`spawndist`,`currentwaypoint`,`curhealth`,`curmana`,`MovementType`,`npcflag`,`unit_flags`,`dynamicflags`) VALUES
(@, 43184, 0, 1, 1, 0, 0, -9203.84, -2155.79, 57.1871, 3.56502, 600, 0, 0, 210, 0, 0, 0, 0, 0);

**Comment by Raydeon** [comment]
We will take a look at this. Thank you again.

Raydeon

**Comment by Raydeon** [comment]
All fixes now need to be done through the forums... This one can be found here
 http://www.projectskyfire.org/index.php?/topic/6690-skyfiredb-fix-submissions-from-blizz-power/

Thanks again for the submission,
 Raydeon
