### ISSUE TITLE
#database instalation problem

### ISSUE THREAD

**Issue by nerv234** [SkyFireArchives/SkyFireDB#36]
When i tried to instal world database: https://github.com/ProjectSkyfire/SkyFireDB/commit/c2be8fbcdac49494612e4f64fa1db5d5353f8ad2
I encountered error:

"error 1064 (42000) at line 2742: you have an error in your SQL syntax; check the manual corresponds to your MySQL server version for the right syntax to use near ' ' at line 1"

I tested it on MySQL server 5.5.10 and 5.5.19.

**Comment by SkyFire** [comment]
I can't reproduce this error. Are you using Linux or windows? Also are you using the installer?

**Comment by Raydeon** [comment]
Same, I cannot get this error, even when I try on my spare pc with only 2 gigs of ram in windows xp

**Comment by nerv234** [comment]
I use win xp, i tried with installer and with heidi sql too.

http://img814.imageshack.us/img814/3538/nowyobrazmapabitowa2x.png
Screen with installer.

It looks finished and succesfully but it isn't all tables in database.

**Comment by nerv234** [comment]
Bump, anyone can help?

**Comment by SkyFire** [comment]
Looks like you need to set your default MySQL configs to use UTF8. Only seems to be an issue with users that don't have utf8 defaulted.
Most installations already set to this. Check this document out. http://dev.mysql.com/doc/refman/5.0/en/charset-connection.html. We will address this on the next update.

**Comment by nerv234** [comment]
Ok, i'll try this but with heidisql i set charset for utf8 when i create world database.

**Comment by nerv234** [comment]
I had already set all configs for utf8, i reconfigure all options, and it don't helps.

**Comment by Raydeon** [comment]
Have you tried to install the release 3 yet?

**Comment by nerv234** [comment]
I write it on my topic on forum, yes, and it helps, sory for not writing here.
