### ISSUE TITLE
NPC: Gilnean Royal Guard

### ISSUE THREAD

**Issue by bkrabach** [SkyFireArchives/SkyFireDB#37]
In the Military District, near the prison, Gilnean Royal Guard walk amongst the Bloodfang Worgen without attacking them, leaving the player to be easily overrun as a number of worgen will attack at once.

**Comment by Raydeon** [comment]
To be quite honest, the worgen area is a mess at the moment. It is, however, on our list of things to address. We will be going through that area very thoroughly in the very near future. I appreciate the input though.

Raydeon

**Comment by bkrabach** [comment]
Sounds good, will hold off on the bug reports in that area then - thanks!

**Comment by Nomadgraphics** [comment]
resolved
