### ISSUE TITLE
Quest: Leader of the Pack

### ISSUE THREAD

**Issue by LetsWoW** [SkyFireArchives/SkyFireDB#38]
NPC Dark Ranger Thyala ist friendly

Fix:
UPDATE `creature_template` SET `faction_A` = 16, `faction_H` = 16 WHERE `entry` = 36312;

**Comment by Raydeon** [comment]
All fixes now need to be done through the forums... This one can be found here
http://www.projectskyfire.org/index.php?/topic/6690-skyfiredb-fix-submissions-from-blizz-power/

Thanks again for the submission,
Raydeon
