### ISSUE TITLE
lot of Gilneas Fixes

### ISSUE THREAD

**Issue by LetsWoW** [SkyFireArchives/SkyFireDB#39]
Fix Gilneas Quest 

-- Grandma's Cat
UPDATE `quest_template` SET `QuestFlags` = 8 WHERE `entry` = 14401;
UPDATE `creature_template` SET `faction_A` = 68, `faction_H` = 68 WHERE `entry` = 36461;
DELETE FROM `creature` WHERE `id`=36461;
INSERT INTO `creature` (`guid`,`id`,`map`,`spawnMask`,`phaseMask`,`modelid`,`equipment_id`,`position_x`,`position_y`,`position_z`,`orientation`,`spawntimesecs`,`spawndist`,`currentwaypoint`,`curhealth`,`curmana`,`MovementType`,`npcflag`,`unit_flags`,`dynamicflags`) VALUES
(15456176, 36461, 654, 1, 1, 0, 0, -2094.98, 2336.6, 8.01807, 2.16393, 300, 0, 0, 343, 0, 0, 0, 0, 0);
-- Ready to Go
UPDATE `quest_template` SET `QuestFlags` = 8 WHERE `entry` = 14402;
-- Hold the Line
UPDATE `quest_template` SET `QuestFlags` = 8 WHERE `entry` = 14347;
-- You Can't Take 'Em Alone
UPDATE `quest_template` SET `QuestFlags` = 8 WHERE `entry` = 14348;
UPDATE `quest_template` SET `ReqCreatureOrGOId1` = 36231 WHERE `entry` = 14348;
-- Holding Steady
UPDATE `quest_template` SET `QuestFlags` = 8 WHERE `entry` = 14366;
-- The Allens' Storm Cellar
UPDATE `quest_template` SET `QuestFlags` = 8 WHERE `entry` = 14367;
-- Escape By Sea
UPDATE `quest_template` SET `QuestFlags` = 8 WHERE `entry` = 14405;
-- Not Quite Shipshape
UPDATE `quest_template` SET `QuestFlags` = 8 WHERE `entry` = 14404;
-- Unleash the Beast
UPDATE `creature_template` SET `faction_A` = 68, `faction_H` = 68 WHERE `entry` = 36810;

**Comment by Raydeon** [comment]
All fixes now need to be done through the forums... This one can be found here
http://www.projectskyfire.org/index.php?/topic/6690-skyfiredb-fix-submissions-from-blizz-power/

Thanks again for the submission,
Raydeon
