### ISSUE TITLE
Questbug - "Extinguishing Hope"

### ISSUE THREAD

**Issue by WoweePaw** [SkyFireArchives/SkyFireDB#4]
Use Milly's Extinguisher to put out 8 Vineyard Fires.
there are no Vineyard Fires so that they can't be counted.

the creature with the id: 42940 is also not counted.
creatures name: Northshire Vineyards Fire Trigger.

Additional Informations:
http://www.wowhead.com/quest=26391

**Comment by Bootz** [comment]
this is a phased quest, this bug track a can be moved to core needs server-side scripting

**Comment by WoweePaw** [comment]
okay...i will move it :)
thanks

**Comment by WoweePaw** [comment]
moved to the bug-tracker:
http://www.projectskyfire.org/bugtracker/view.php?id=277
