### ISSUE TITLE
Quest: Two By Sea

### ISSUE THREAD

**Issue by LetsWoW** [SkyFireArchives/SkyFireDB#40]
Need Spell fix http://www.wowhead.com/spell=68659

-- Two By Sea http://www.wowhead.com/quest=14382
DELETE FROM `creature` WHERE `id`=36283;
INSERT INTO `creature` (`guid`,`id`,`map`,`spawnMask`,`phaseMask`,`modelid`,`equipment_id`,`position_x`,`position_y`,`position_z`,`orientation`,`spawntimesecs`,`spawndist`,`currentwaypoint`,`curhealth`,`curmana`,`MovementType`,`npcflag`,`unit_flags`,`dynamicflags`) VALUES
(@, 36283, 654, 1, 65534, 0, 0, -2138.32, 2505.71, 4.84951, 5.89379, 300, 0, 0, 420, 0, 0, 0, 0, 0),
(@, 36283, 654, 1, 65534, 0, 0, -2155.99, 2523.33, 5.12479, 5.60713, 300, 0, 0, 420, 0, 0, 0, 0, 0),
(@, 36283, 654, 1, 65534, 0, 0, -2149.2, 2550.58, 4.22256, 5.72886, 300, 0, 0, 420, 0, 0, 0, 0, 0),
(@, 36283, 654, 1, 65534, 0, 0, -2123.19, 2541.28, 5.47634, 5.88201, 300, 0, 0, 420, 0, 0, 0, 0, 0),
(@, 36283, 654, 1, 65534, 0, 0, -2120.96, 2564.52, 5.32531, 5.8074, 300, 0, 0, 420, 0, 0, 0, 0, 0),
(@, 36283, 654, 1, 65534, 0, 0, -2105.19, 2546.77, 4.97786, 6.10978, 300, 0, 0, 420, 0, 0, 0, 0, 0),
(@, 36283, 654, 1, 65534, 0, 0, -2077.58, 2604.6, 5.22659, 4.94997, 300, 0, 0, 1370, 0, 0, 0, 0, 0);
UPDATE `creature_template` SET `minlevel` = 7, `maxlevel` = 7, `mechanic_immune_mask` = 0 WHERE `entry` = 36283;
UPDATE `creature_template` SET `unit_flags` = 16384, `type_flags` = 393256, `VehicleId` = 438, `movementId` = 207 WHERE `entry` = 36283;
DELETE FROM `npc_spellclick_spells` WHERE `npc_entry`=36283;
INSERT INTO `npc_spellclick_spells` (`npc_entry`, `spell_id`, `quest_start`, `quest_start_active`, `quest_end`, `cast_flags`, `aura_required`, `aura_forbidden`, `user_type`) values(36283,69434,14382,1,14382,1,0,0,0);
UPDATE `creature_template` SET `minlevel` = 6, `maxlevel` = 7, `faction_A` = 68, `faction_H` = 68, `mingold` = 7, `maxgold` = 11, `Health_mod` = 137.0 WHERE `entry` = 36397;
UPDATE `creature_template` SET `minlevel` = 6, `maxlevel` = 7, `faction_A` = 68, `faction_H` = 68, `mingold` = 7, `maxgold` = 11, `Health_mod` = 137.0 WHERE `entry` = 36399;

**Comment by Raydeon** [comment]
All fixes now need to be done through the forums... This one can be found here
http://www.projectskyfire.org/index.php?/topic/6690-skyfiredb-fix-submissions-from-blizz-power/

Thanks again for the submission,
Raydeon
