### ISSUE TITLE
NPC: Shadowhide Warrior

### ISSUE THREAD

**Issue by LetsWoW** [SkyFireArchives/SkyFireDB#42]
too high Damage, 7k with level 20 NICE :)
Problem wrong Spell in AI

fix:
UPDATE `creature_ai_scripts` SET `action1_param1` = 34510 WHERE `id` = 30005101;

**Comment by Raydeon** [comment]
All fixes now need to be done through the forums... This one can be found here
http://www.projectskyfire.org/index.php?/topic/6690-skyfiredb-fix-submissions-from-blizz-power/

Thanks again for the submission,
Raydeon
