### ISSUE TITLE
NPC: Queen Mia Greymane

### ISSUE THREAD

**Issue by LetsWoW** [SkyFireArchives/SkyFireDB#43]
Fix this NPC with 

UPDATE `creature_template` SET `minlevel` = 7, `maxlevel` = 7, `faction_A` = 2164, `faction_H` = 2164, `mingold` = 5, `maxgold` = 15 WHERE `entry` = 36606;

DELETE FROM `creature` WHERE `id`=36606;
INSERT INTO `creature` (`guid`,`id`,`map`,`spawnMask`,`phaseMask`,`modelid`,`equipment_id`,`position_x`,`position_y`,`position_z`,`orientation`,`spawntimesecs`,`spawndist`,`currentwaypoint`,`curhealth`,`curmana`,`MovementType`,`npcflag`,`unit_flags`,`dynamicflags`) VALUES
(@, 36606, 0, 1, 1, 0, 0, -1584.56, 2552.58, 130.218, 3.86766, 600, 0, 0, 188, 0, 0, 0, 0, 0),
(@, 36606, 654, 1, 65534, 0, 0, -1582.93, 2554.58, 130.219, 4.06087, 300, 0, 0, 137, 0, 0, 0, 0, 0);

DELETE FROM `creature_questrelation` WHERE `id` = 36606;
INSERT INTO `creature_questrelation` (`id`,`quest`) VALUES (36606,14466);
DELETE FROM `creature_involvedrelation` WHERE `id` = 36606;
INSERT INTO `creature_involvedrelation` (`id`,`quest`) VALUES (36606,14465);

**Comment by Raydeon** [comment]
All fixes now need to be done through the forums... This one can be found here
http://www.projectskyfire.org/index.php?/topic/6690-skyfiredb-fix-submissions-from-blizz-power/

Thanks again for the submission,
Raydeon
