### ISSUE TITLE
All Vehicles IDs

### ISSUE THREAD

**Issue by specters** [SkyFireArchives/SkyFireDB#45]
I faced a problem with sacrificed quest,that needs a vehicle named crowley's horse.
can you help me to find vehicle IDs?
I used many of vehicles but I can't get my character on them.
And I think,I need some npc_flags and unit_flags too

**Comment by Raydeon** [comment]
Someone has already replied to your post on the forums here: http://www.projectskyfire.org/index.php?/topic/6541-vehicles-ids/ The vehicle IDs are located in Vehicle.dbc. You will have to test out every individual vehicle id until you find the vehicle you are looking for, as they are not labeled. This takes hours, if not days in most cases. 

NOTE: In the future, please do NOT post help requests in the bug tracker.

Raydeon

**Comment by specters** [comment]
ok thx dude
but I think it's a bug for sacreficed quest

**Comment by Raydeon** [comment]
Ok, I will add this to my todo list... thanks for reporting it

**Comment by LetsWoW** [comment]
UPDATE `creature_template` SET `dynamicflags` = 8, `type_flags` = 262144, `VehicleId` = 349 WHERE `entry` = 44427;

**Comment by specters** [comment]
thx you dude,
you saved my ass!

**Comment by Nomadgraphics** [comment]
resolved
