### ISSUE TITLE
character_stats error..

### ISSUE THREAD

**Issue by luckyzero** [SkyFireArchives/SkyFireDB#47]
//
SQL: INSERT INTO character_stats (guid, maxhealth, maxpower1, maxpower2, maxpowe
r3, maxpower4, maxpower5, maxpower6, maxpower7, maxpower8, maxpower9, maxpower10
, strength, agility, stamina, intellect, spirit, armor, resHoly, resFire, resNat
ure, resFrost, resShadow, resArcane, blockPct, dodgePct, parryPct, critPct, rang
edCritPct, spellCritPct, attackPower, rangedAttackPower, spellPower, resilience)
 VALUES (3,41489,0,1000,0,100,0,0,1000,0,0,0,119,218,114,49,69,0,0,0,0,0,0,0,0,0
,0,0,0,0,487,293,0)
ERROR: [1136] Column count doesn't match value count at row 1
Unhandled MySQL errno 1136. Unexpected behaviour possible.
[Warning] Transaction aborted. 42 queries not executed.
//
error  T_T
i bad english.. sorry
MYSQL 5.5.9 use..
windows7 64bit 
sky core last..
sky db level 3

**Comment by Bootz** [comment]
Fixed in commit fb58898ccad2e1b0b7ddd2bd9108d30f1a46fdfb

**Comment by luckyzero** [comment]
thanks ^_^ thanks..
