### ISSUE TITLE
Quest: In Defense of Quel'Danil (27625)

### ISSUE THREAD

**Issue by AriDEV** [SkyFireArchives/SkyFireDB#48]
Quest: http://www.wowhead.com/quest=27625
Npc: http://www.wowhead.com/npc=43541

Quest cant be completed because NPC 43541 is missing in the creature_template and is not spawned.

Signed-off-by: AriDEV AriDEV@Azet.sk

**Comment by Raydeon** [comment]
Thank you, I'll add this to my list of things to do

Raydeon

**Comment by Raydeon** [comment]
The spawns along with their proper faction/combatAI/level, etc are now in developer database being tested. Only thing left is to script the fights between these guys and the Sentries, which will have to be done at a later day. At least now you can complete the quest. - These spawns will be in the next release.. likely this coming Sunday.

Raydeon
