### ISSUE TITLE
Questbug - "A Spirit Ally?"

### ISSUE THREAD

**Issue by WoweePaw** [SkyFireArchives/SkyFireDB#5]
The Quest doesn't work. When you use the Totem to call the ghost, he don't appear.

Additional Informations:
http://www.wowhead.com/quest=9847 <- Quest
http://www.wowhead.com/item=24498 <- Totem-ID

**Comment by SkyFire** [comment]
Will look into this issue

**Comment by WoweePaw** [comment]
nice :)
