### ISSUE TITLE
Various trolls quest fix

### ISSUE THREAD

**Issue by anubislinux** [SkyFireArchives/SkyFireDB#51]
i put here for those servers that the trolls can only do the first quest and then there is no more
execute the query in the world DB

UPDATE `quest_template` SET `PrevQuestId`=24764 WHERE `entry`=24765 LIMIT 1;
UPDATE `quest_template` SET `PrevQuestId`=24750 WHERE `entry`=24639 LIMIT 1;
UPDATE `quest_template` SET `PrevQuestId`=24758 WHERE `entry`=24751 LIMIT 1;
UPDATE `quest_template` SET `PrevQuestId`=24607 WHERE `entry`=24759 LIMIT 1;
UPDATE `quest_template` SET `PrevQuestId`=24770 WHERE `entry`=24771 LIMIT 1;
UPDATE `quest_template` SET `PrevQuestId`=24782 WHERE `entry`=24783 LIMIT 1;
UPDATE `quest_template` SET `PrevQuestId`=26272 WHERE `entry`=26273 LIMIT 1;
UPDATE `quest_template` SET `RequiredRaces`=946 WHERE `entry`=24639 LIMIT 1;
UPDATE `quest_template` SET `RequiredRaces`=946 WHERE `entry`=24751 LIMIT 1;
UPDATE `quest_template` SET `RequiredRaces`=946 WHERE `entry`=24759 LIMIT 1;
UPDATE `quest_template` SET `RequiredRaces`=946 WHERE `entry`=24765 LIMIT 1;
UPDATE `quest_template` SET `RequiredRaces`=946 WHERE `entry`=24771 LIMIT 1;
UPDATE `quest_template` SET `RequiredRaces`=946 WHERE `entry`=24777 LIMIT 1;
UPDATE `quest_template` SET `RequiredRaces`=946 WHERE `entry`=24783 LIMIT 1;
UPDATE `quest_template` SET `RequiredRaces`=946 WHERE `entry`=26273 LIMIT 1;
UPDATE `quest_template` SET `PrevQuestId`=24750 WHERE `entry`=24751 LIMIT 1;
UPDATE `quest_template` SET `PrevQuestId`=24758 WHERE `entry`=24759 LIMIT 1;
UPDATE `quest_template` SET `PrevQuestId`=24607 WHERE `entry`=24639 LIMIT 1;
UPDATE `quest_template` SET `RequiredRaces`=946 WHERE `entry`=24642 LIMIT 1;
UPDATE `quest_template` SET `RequiredRaces`=946 WHERE `entry`=24754 LIMIT 1;
UPDATE `quest_template` SET `RequiredRaces`=946 WHERE `entry`=24762 LIMIT 1;
UPDATE `quest_template` SET `RequiredRaces`=946 WHERE `entry`=24768 LIMIT 1;
UPDATE `quest_template` SET `RequiredRaces`=946 WHERE `entry`=24774 LIMIT 1;
UPDATE `quest_template` SET `RequiredRaces`=946 WHERE `entry`=24780 LIMIT 1;
UPDATE `quest_template` SET `RequiredRaces`=946 WHERE `entry`=24786 LIMIT 1;
UPDATE `quest_template` SET `RequiredRaces`=946 WHERE `entry`=26276 LIMIT 1;
UPDATE `quest_template` SET `PrevQuestId`=24641 WHERE `entry`=24642 LIMIT 1;
UPDATE `quest_template` SET `PrevQuestId`=24753 WHERE `entry`=24754 LIMIT 1;
UPDATE `quest_template` SET `PrevQuestId`=24761 WHERE `entry`=24762 LIMIT 1;
UPDATE `quest_template` SET `PrevQuestId`=24767 WHERE `entry`=24768 LIMIT 1;
UPDATE `quest_template` SET `PrevQuestId`=24773 WHERE `entry`=24774 LIMIT 1;
UPDATE `quest_template` SET `PrevQuestId`=24779 WHERE `entry`=24780 LIMIT 1;
UPDATE `quest_template` SET `PrevQuestId`=24785 WHERE `entry`=24786 LIMIT 1;
UPDATE `quest_template` SET `PrevQuestId`=26275 WHERE `entry`=26276 LIMIT 1;
UPDATE `quest_template` SET `ObjectiveText1`='' WHERE `entry`=24642 LIMIT 1;
UPDATE `quest_template` SET `ObjectiveText1`='' WHERE `entry`=24754 LIMIT 1;
UPDATE `quest_template` SET `ObjectiveText1`='' WHERE `entry`=24762 LIMIT 1;
UPDATE `quest_template` SET `ObjectiveText1`='' WHERE `entry`=24768 LIMIT 1;
UPDATE `quest_template` SET `ObjectiveText1`='' WHERE `entry`=24774 LIMIT 1;
UPDATE `quest_template` SET `ObjectiveText1`='' WHERE `entry`=24780 LIMIT 1;
UPDATE `quest_template` SET `ObjectiveText1`='' WHERE `entry`=24786 LIMIT 1;
UPDATE `quest_template` SET `ObjectiveText1`='' WHERE `entry`=26276 LIMIT 1;
UPDATE `quest_template` SET `ReqCreatureOrGOId1`=38142, `ReqCreatureOrGOId2`=0 WHERE `entry`=26276 LIMIT 1;
UPDATE `quest_template` SET `ReqCreatureOrGOId1`=38142 WHERE `entry`=24786 LIMIT 1;
UPDATE `quest_template` SET `ReqCreatureOrGOId1`=38142 WHERE `entry`=24780 LIMIT 1;
UPDATE `quest_template` SET `ReqCreatureOrGOId1`=38142 WHERE `entry`=24774 LIMIT 1;
UPDATE `quest_template` SET `ReqCreatureOrGOId1`=38142 WHERE `entry`=24768 LIMIT 1;
UPDATE `quest_template` SET `ReqCreatureOrGOId1`=38142 WHERE `entry`=24762 LIMIT 1;
UPDATE `quest_template` SET `ReqCreatureOrGOId1`=38142 WHERE `entry`=24754 LIMIT 1;
UPDATE `quest_template` SET `ReqCreatureOrGOId1`=38142, `ReqCreatureOrGOId2`=0 WHERE `entry`=24642 LIMIT 1;
UPDATE `quest_template` SET `ReqCreatureOrGOId2`=0 WHERE `entry`=24754 LIMIT 1;
UPDATE `quest_template` SET `ReqCreatureOrGOId2`=0 WHERE `entry`=24762 LIMIT 1;
UPDATE `quest_template` SET `ReqCreatureOrGOId2`=0 WHERE `entry`=24768 LIMIT 1;
UPDATE `quest_template` SET `ReqCreatureOrGOId2`=0 WHERE `entry`=24774 LIMIT 1;
UPDATE `quest_template` SET `ReqCreatureOrGOId2`=0 WHERE `entry`=24780 LIMIT 1;
UPDATE `quest_template` SET `ReqCreatureOrGOId2`=0 WHERE `entry`=24786 LIMIT 1;
UPDATE `quest_template` SET `ReqCreatureOrGOCount2`=0 WHERE `entry`=26276 LIMIT 1;
UPDATE `quest_template` SET `ReqCreatureOrGOCount2`=0 WHERE `entry`=24786 LIMIT 1;
UPDATE `quest_template` SET `ReqCreatureOrGOCount2`=0 WHERE `entry`=24780 LIMIT 1;
UPDATE `quest_template` SET `ReqCreatureOrGOCount2`=0 WHERE `entry`=24774 LIMIT 1;
UPDATE `quest_template` SET `ReqCreatureOrGOCount2`=0 WHERE `entry`=24768 LIMIT 1;
UPDATE `quest_template` SET `ReqCreatureOrGOCount2`=0 WHERE `entry`=24762 LIMIT 1;
UPDATE `quest_template` SET `ReqCreatureOrGOCount2`=0 WHERE `entry`=24754 LIMIT 1;
UPDATE `quest_template` SET `ReqCreatureOrGOCount2`=0 WHERE `entry`=24642 LIMIT 1;
UPDATE `creature_template` SET `npcflag`=0, `unit_flags`=0, `dynamicflags`=8 WHERE `entry`=38142 LIMIT 1;
UPDATE `quest_template` SET `RequiredRaces`=946 WHERE `entry`=26274 LIMIT 1;
UPDATE `quest_template` SET `RequiredRaces`=946 WHERE `entry`=24784 LIMIT 1;
UPDATE `quest_template` SET `RequiredRaces`=946 WHERE `entry`=24778 LIMIT 1;
UPDATE `quest_template` SET `RequiredRaces`=946 WHERE `entry`=24772 LIMIT 1;
UPDATE `quest_template` SET `RequiredRaces`=946 WHERE `entry`=24766 LIMIT 1;
UPDATE `quest_template` SET `RequiredRaces`=946 WHERE `entry`=24760 LIMIT 1;
UPDATE `quest_template` SET `RequiredRaces`=946 WHERE `entry`=24752 LIMIT 1;
UPDATE `quest_template` SET `RequiredRaces`=946 WHERE `entry`=24640 LIMIT 1;

**Comment by Raydeon** [comment]
Sorry, there are far too many mistakes in here. Of the ones that are not mistakes, our database already has. Which database are you running? Almost all of these quests have been fixed in our database weeks ago... some of these would actually break the quests. In the future, please ONLY submit fixes that our database needs, along with an explaination of what whats broken, as well as how your solution fixes the issue.

An example of a major mistake: 
"UPDATE quest_template SET ReqCreatureOrGOId1=38142, ReqCreatureOrGOId2=0 WHERE entry=26276 LIMIT 1;" 
This is not correct. Killing creature 38142 is actually objective number 2 of this quest. Objective number 1 would be to speak with npc Jailor. This was verified on live servers and is already fully functional in our database. Furthermore, our database has SAI which requires a specific quest requirement for npc Jailor to open the cage. Your "fix" would break that functionality.

Raydeon
