### ISSUE TITLE
Dump characters fixed

### ISSUE THREAD

**Issue by LKArthas** [SkyFireArchives/SkyFireDB#52]
In every cataclysm server i tested, there was no one that can dump your characters, no skyfire no arkcore, i start work at that problem and i reach its solution
you only need to add this query to the characters database, the dump problems resides in the tables ammoid that report Can´t be null, so i allow it to null, and then action bars say the same problem, the same action bars allow null and is fixed, i have already tested and id dump my character without any problem, even when you don´t see your saved secondary actionbars, you just need to activate at game and is fixed

ALTER TABLE `characters`  CHANGE COLUMN `actionBars` `actionBars` TINYINT(3) UNSIGNED NULL DEFAULT '0' AFTER `knownTitles`;
ALTER TABLE `characters`  CHANGE COLUMN `ammoId` `ammoId` INT(10) NULL DEFAULT '0' AFTER `equipmentCache`;

**Comment by SkyFire** [comment]
Arkcore will not have it fixed until we fix it. They copy our stuff. :) Anyways. I will fix it shortly.

**Comment by Bootz** [comment]
- ALTER TABLE characters CHANGE COLUMN ammoId ammoId INT(10) NULL DEFAULT '0' AFTER equipmentCache;

there is no ammoId... thats was removed awhile ago. since cata uses ammo completely differently

**Comment by LKArthas** [comment]
thank you for answer me so fast, can you tell me in what version of
the skyfire server you have already fixed, and better if you tested
the dump player function :-), Count with me for testing Databases, the
server i have installed now is skyfire is the most stable right now,
loads with almost no errors, i have 9 players testing the server with
me, i have installed a patch recently downloaded from your server
SkyFire DB NG Release <3> 2012_3_04 & "patch" SmartAI Lab 406.01, i
kepp testing it, send you if i have something morre to fix, i will be
better if i have the same server that you guys are working to fix.
Best regards
Working for a better server of WOW (go skyfire team)

i will send more issues soon, as soon i find it or fix it

LK_@RTH@§
its a shame that the webpage does not let put my nickname, thats life

**Comment by Bootz** [comment]
everything you need is right here.
https://github.com/ProjectSkyfire/SkyFireEMU
look in downloads or here for public db. (btw its on v004, 003 is old)  ;)

**Comment by Nomadgraphics** [comment]
resolved
