### ISSUE TITLE
Problem in the flight paths

### ISSUE THREAD

**Issue by LKArthas** [SkyFireArchives/SkyFireDB#53]
i have the most recent vercion of skyfire server, and have a problem that i believe that resides in the core not in the DB, the flight routes don´t goes well, if you disable the instant flight paths from the servers config file, you stay giving rounds by the starting flying point, you dont reach its destiny
and the same flight paths problem is even when you disable allflightpath option from the server config file, you still have it when you create a new character, i don´t know the rest of the folks, but i really enjoy playing WoW blizzlike
can you fix this issue

**Comment by SkyFire** [comment]
How is this DB related?
