### ISSUE TITLE
Fixed a problem with the quest the ravaged caravan

### ISSUE THREAD

**Issue by LKArthas** [SkyFireArchives/SkyFireDB#54]
the problem was that the sealed supply crate that you must open to end the quest and start the another was not properly working, i have a fix for it, already tested Works!

INSERT INTO `gameobject_involvedrelation` (`id`, `quest`) VALUES (2908, 749);

**Comment by Nomadgraphics** [comment]
I tested this on our db and it was already working. Therefore this fix is not needed
