### ISSUE TITLE
Nimboya not exist

### ISSUE THREAD

**Issue by djcenox** [SkyFireArchives/SkyFireDB#58]
npc 2497 seems not exist in Grom'gol Base Camp.
http://justmegawatt.com/readables/everythingelse/worldofwarcraft/creaturelist 
(Tried to spawn as GM)

**Comment by Nomadgraphics** [comment]
I have no idea why you wrote this. He is spawned correctly.

**Comment by djcenox** [comment]
if you say so. and i cannot spawn it as gm means that my db is corrupted.

**Comment by djcenox** [comment]
Ok now it spawn but i can see him only on with gm on... is it normal?

**Comment by Nomadgraphics** [comment]
use this query on your db it will fix the issue. Thank you for your report.

DELETE FROM `creature_template_addon` WHERE (`entry`=2497);
INSERT INTO `creature_template_addon` (`entry`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `auras`) VALUES (2497, 0, 0, 65536, 257, 0, '');

**Comment by djcenox** [comment]
done thanks.

**Comment by djcenox** [comment]
Better someone add this to an update.

**Comment by Nomadgraphics** [comment]
I always add the fixes to update. It will be released in the next update.
