### ISSUE TITLE
The Endles flow quest

### ISSUE THREAD

**Issue by djcenox** [SkyFireArchives/SkyFireDB#61]
The endless flow quest i guess is bugged cause handmade granade don't "disable" Scourge Bone Animus.

**Comment by djcenox** [comment]
Neither Supporting the Troops seems working, killing Andohral Guard not increase the counter.

**Comment by djcenox** [comment]
http://www.wowpedia.org/Quest:The_Endless_Flow

http://www.wowpedia.org/Quest:Supporting_the_Troops

**Comment by Nomadgraphics** [comment]
ok.... I have this quest working correctly now. It will be in the next release of the database. 

In the future please submit your broken quest reports in this format:

http://www.wowhead.com/quest=26922    Quest: The Endless Flow

issue: Jearl's Hand Grenade is not working on the Scourge Bone Animus
