### ISSUE TITLE
Marg Speaks

### ISSUE THREAD

**Issue by djcenox** [SkyFireArchives/SkyFireDB#72]
http://www.wowpedia.org/Quest:Marg_Speaks
Nazeer don't have the quest(for completing)

**Comment by Nomadgraphics** [comment]
http://www.wowhead.com/quest=1261/marg-speaks

This quest was marked obsolete by Blizzard and cannot be obtained or completed.

if you would use wowhead.com like I ask you to then we wouldn't have this kind of report.
