### ISSUE TITLE
Duskwing

### ISSUE THREAD

**Issue by djcenox** [SkyFireArchives/SkyFireDB#73]
http://www.wowhead.com/quest=27523
Bugged, unable to engage the duskwing.

**Comment by Nomadgraphics** [comment]
no link from wowhead no fix your quest last time I tell you this

**Comment by djcenox** [comment]
http://www.wowhead.com/quest=27523
Sorry i posted before read that you need from wowhead.

**Comment by Nomadgraphics** [comment]
Fixed, will be in next database update

Thanks for the Wowhead links.
