### ISSUE TITLE
The bad dogs

### ISSUE THREAD

**Issue by djcenox** [SkyFireArchives/SkyFireDB#92]
http://www.wowhead.com/quest=27890

The guys are only visible in gm mode. I guess i same problem that i had with Nimboya.
I dunno if other bad dogs guys are needed for other quests but all 3 are invisible.

**Comment by Nomadgraphics** [comment]
Fixed, will be in next update

 I corrected this issue  for all three npc's: Amakkar, Gargal, and Jurrix Whitemane

thanks for this report. If you find more of this issue with npc's only showing up in GM mode please post.
