### ISSUE TITLE
Problem with a quest of razor Hill and some NPCs

### ISSUE THREAD

**Issue by LKArthas** [SkyFireArchives/SkyFireDB#93]
there is a problem with the quest The burning Blade in razor hill (http://www.wowhead.com/quest=25232) there aren´t burning blade members in duskwind caverns, instead there are only the harpies from original wow, this must be replaced for the Burning blade Members

and the other part with Npcs issue is that in the burning blade cave (east of orgrimmar) the warlocks have voidwalkers as minios with 500 HP (Acceptable) to 5746 (absolutely unnaceptable for a LVL 8 - 9 creature)

**Comment by Nomadgraphics** [comment]
What database are you using? I did this quest today and there aren't any harpies in that cave only burning blade members.

Burning Blade Cave? Do you mean Skull Rock? In our database the Voidwalker Minion's HP is 838

**Comment by LKArthas** [comment]
i already see my error i was finding in the wrong place But the
voidwalkers HP its a real issue and i have the latest db downloaded
from github itself and hav the HP problem some of the voidwalkers are
good in HP but others have a terrible ammout of HP

**Comment by Nomadgraphics** [comment]
ok I fixed the HP on the Minion's. Someone had them set to level 9-80 lol. This will be included in the next release

**Comment by LKArthas** [comment]
thank you :)
