### ISSUE TITLE
Gadgetzan

### ISSUE THREAD

**Issue by djcenox** [SkyFireArchives/SkyFireDB#98]
Goblin commoner a Gadgetzan are all invisible with exclamation mar on their head.
Dr. Dealwell(http://www.wowhead.com/npc=39034) quest starts/end without doing nothing, only speaking.

**Comment by Nomadgraphics** [comment]
ouch! yep, it's in bad shape. I have the Goblin commoner corrected now, and I will fix the other issues too. Will post back when I have this completed. Thank you for the report.

**Comment by DigiD702** [comment]
We have these issues completed :) thank you for the report
